apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  serviceName: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /logs
          name: yunpanpvc
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: jvessel-secret
  volumeClaimTemplates:
  - metadata:
      name: yunpanpvc
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: "default"
      resources:
        requests:
          storage: 20Gi
