apiVersion: v1
kind: Secret
metadata:
  name: jvessel-secret
  namespace: guestbook-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJqdmVzc2VsdjItZG9ja2VyaHViLWJqLmpkY2xvdWQuY29tIjp7InVzZXJuYW1lIjoiSnZlc3NlbFYyIiwicGFzc3dvcmQiOiJKdmVzc2VsMjAyMCIsImF1dGgiOiJTblpsYzNObGJGWXlPa3AyWlhOelpXd3lNREl3In19fQ==
